services:
  - type: web
    name: evolvenet
    env: node
    rootDir: ./
    buildCommand: npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
